parameters:
    # Adds a fallback DATABASE_URL if the env var is not set.
    # This allows you to run cache:warmup even if your
    # environment variables are not available yet.
    # You should not need to change this value.
    env(DATABASE_URL): ''

doctrine:
    dbal:
        # configure these for your database server
        default_connection: default
        connections:
            default:
                driver: 'pdo_mysql'
                server_version: '5.7'
                charset: utf8mb4
                default_table_options:
                    charset: utf8mb4
                    collate: utf8mb4_unicode_ci

                url: '%env(resolve:DATABASE_SDPD_URL)%'
            IFG_TEST2:
                driver: 'pdo_pgsql'
                server_version: '7.2'
                charset: utf8
                default_table_options:
                    charset: utf8
                    collate: utf8_unicode_ci

                url: '%env(resolve:DATABASE_TEST2_URL)%'
        
    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        default_entity_manager: default
        entity_managers:
            default:
                connection: default
                naming_strategy: doctrine.orm.naming_strategy.underscore
                auto_mapping: true
                mappings:
                    IFG_SDPD:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/Entity/IFG_SDPD'
                        prefix: 'App\Entity\IFG_SDPD'
                        alias: IFG_SDPD
            IFG_TEST2:
                connection: IFG_TEST2
                naming_strategy: doctrine.orm.naming_strategy.underscore
                mappings:
                    IFG_TEST2:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/Entity/IFG_TEST2'
                        prefix: 'App\Entity\IFG_TEST2'
                        alias: IFG_TEST2